"""empty message

Revision ID: 0530759d1bf6
Revises: 6a5c1e295f2c
Create Date: 2025-08-02 20:36:28.795529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0530759d1bf6'
down_revision = '6a5c1e295f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_autonomos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ano_exercicio', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_autonomos', schema=None) as batch_op:
        batch_op.drop_column('ano_exercicio')

    # ### end Alembic commands ###
