"""Adiciona campo para foto do teste rapido em SolicitacaoCalazar

Revision ID: 0ad5efa0eb76
Revises: 1b81982ac309
Create Date: 2025-08-03 21:15:36.743130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad5efa0eb76'
down_revision = '1b81982ac309'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes_calazar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_teste_rapido_path', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitacoes_calazar', schema=None) as batch_op:
        batch_op.drop_column('foto_teste_rapido_path')

    # ### end Alembic commands ###
