"""Adiciona campos de endereço à tabela Empresas

Revision ID: 15ab5a2c690b
Revises: b0401a63e1d3
Create Date: 2025-07-30 17:12:41.786517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ab5a2c690b'
down_revision = 'b0401a63e1d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logradouro', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('uf', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('cep')
        batch_op.drop_column('uf')
        batch_op.drop_column('numero')
        batch_op.drop_column('logradouro')

    # ### end Alembic commands ###
