"""Cria tabela para pessoa fisica

Revision ID: 1e01fb1b66b8
Revises: e0aace96861f
Create Date: 2025-07-23 16:33:09.186835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e01fb1b66b8'
down_revision = 'e0aace96861f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas_fisicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('orgao_expedidor', sa.String(length=20), nullable=True),
    sa.Column('uf_rg', sa.String(length=2), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('telefone_contato', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('endereco_local', sa.String(length=250), nullable=True),
    sa.Column('tipo_local', sa.String(length=100), nullable=True),
    sa.Column('situacao_local', sa.JSON(), nullable=True),
    sa.Column('finalidade_cadastro', sa.JSON(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pessoas_fisicas')),
    sa.UniqueConstraint('cpf', name=op.f('uq_pessoas_fisicas_cpf'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pessoas_fisicas')
    # ### end Alembic commands ###
