"""Adiciona campos de RT às licenças

Revision ID: 1fa78f451c44
Revises: 15ab5a2c690b
Create Date: 2025-07-30 17:24:23.892286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa78f451c44'
down_revision = '15ab5a2c690b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rt_nome', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('rt_conselho', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('rt_numero', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_empresas', schema=None) as batch_op:
        batch_op.drop_column('rt_numero')
        batch_op.drop_column('rt_conselho')
        batch_op.drop_column('rt_nome')

    # ### end Alembic commands ###
