"""Renomeia Fiscal para Funcionario e adiciona cargo

Revision ID: 2b01b1538d82
Revises: 659cbb9b6ff7
Create Date: 2025-07-31 18:32:27.429343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b01b1538d82'
down_revision = '659cbb9b6ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('cargo', sa.String(length=50), nullable=False),
    sa.Column('caminho_assinatura', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_funcionarios')),
    sa.UniqueConstraint('matricula', name=op.f('uq_funcionarios_matricula'))
    )
    op.drop_table('fiscais')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiscais',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cpf', sa.VARCHAR(length=14), nullable=True),
    sa.Column('nome', sa.VARCHAR(length=120), nullable=False),
    sa.Column('matricula', sa.VARCHAR(length=64), nullable=True),
    sa.Column('caminho_assinatura', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fiscais')),
    sa.UniqueConstraint('cpf', name=op.f('uq_fiscais_cpf')),
    sa.UniqueConstraint('matricula', name=op.f('uq_fiscais_matricula'))
    )
    op.drop_table('funcionarios')
    # ### end Alembic commands ###
