"""Cria tabela Fiscal e adiciona relação com User

Revision ID: 34b855ceaf33
Revises: 939875c276ca
Create Date: 2025-07-23 14:24:14.547008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b855ceaf33'
down_revision = '939875c276ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiscais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('matricula', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_fiscais_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fiscais')),
    sa.UniqueConstraint('email', name=op.f('uq_fiscais_email')),
    sa.UniqueConstraint('matricula', name=op.f('uq_fiscais_matricula'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_constraint(batch_op.f('uq_user_matricula'), type_='unique')
        batch_op.drop_column('matricula')
        batch_op.drop_column('nome')
        batch_op.drop_column('telefone')
        batch_op.drop_column('email')
        batch_op.drop_column('funcao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funcao', sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=120), nullable=False))
        batch_op.add_column(sa.Column('matricula', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_matricula'), ['matricula'])
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=1)

    op.drop_table('fiscais')
    # ### end Alembic commands ###
