"""Adiciona horario e modalidade a autonomos

Revision ID: 368e41cf2d94
Revises: 3c8a4c687943
Create Date: 2025-07-24 15:50:02.733987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368e41cf2d94'
down_revision = '3c8a4c687943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autonomos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horario_funcionamento', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('modalidade_atendimento', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autonomos', schema=None) as batch_op:
        batch_op.drop_column('modalidade_atendimento')
        batch_op.drop_column('horario_funcionamento')

    # ### end Alembic commands ###
