"""Adiciona coluna autonomo_id a tabela licencas

Revision ID: 37e43484d25c
Revises: 368e41cf2d94
Create Date: 2025-07-26 14:08:32.343715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e43484d25c'
down_revision = '368e41cf2d94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autonomo_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_licencas_autonomo_id_autonomos'), 'autonomos', ['autonomo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_licencas_autonomo_id_autonomos'), type_='foreignkey')
        batch_op.drop_column('autonomo_id')

    # ### end Alembic commands ###
