"""Adiciona campos detalhados a licenca de evento

Revision ID: 3b5ba61796b6
Revises: 6d8c7ef18292
Create Date: 2025-07-29 00:10:16.507317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '3b5ba61796b6'
down_revision = '6d8c7ef18292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estrutura_detalhes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('bombeiros_numero', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('bombeiros_data', sa.Date(), nullable=True))
        batch_op.drop_column('estrutura')
        batch_op.drop_column('bombeiros_anexo_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bombeiros_anexo_path', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('estrutura', sqlite.JSON(), nullable=True))
        batch_op.drop_column('bombeiros_data')
        batch_op.drop_column('bombeiros_numero')
        batch_op.drop_column('estrutura_detalhes')

    # ### end Alembic commands ###
