"""Adiciona protocolo a autonomo, pessoa fisica e cria tabela de licenca de evento

Revision ID: 3c8a4c687943
Revises: 309e71d726ae
Create Date: 2025-07-23 17:10:00.782552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8a4c687943'
down_revision = '309e71d726ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licencas_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo', sa.String(length=50), nullable=True),
    sa.Column('nome_evento', sa.String(length=150), nullable=False),
    sa.Column('organizador_nome', sa.String(length=150), nullable=False),
    sa.Column('organizador_cpf_cnpj', sa.String(length=18), nullable=False),
    sa.Column('local_evento', sa.String(length=250), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('publico_estimado', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licencas_eventos')),
    sa.UniqueConstraint('protocolo', name=op.f('uq_licencas_eventos_protocolo'))
    )
    with op.batch_alter_table('autonomos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protocolo', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_autonomos_protocolo'), ['protocolo'])

    with op.batch_alter_table('pessoas_fisicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protocolo', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_pessoas_fisicas_protocolo'), ['protocolo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoas_fisicas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_pessoas_fisicas_protocolo'), type_='unique')
        batch_op.drop_column('protocolo')

    with op.batch_alter_table('autonomos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_autonomos_protocolo'), type_='unique')
        batch_op.drop_column('protocolo')

    op.drop_table('licencas_eventos')
    # ### end Alembic commands ###
