"""Adiciona campos de documentos ao modelo Autonomo

Revision ID: 4b27cb561c8a
Revises: c2a6db58d5a0
Create Date: 2025-08-01 16:57:29.873547

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '4b27cb561c8a'
down_revision = 'c2a6db58d5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autonomos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('doc_alvara_funcionamento_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('doc_cpf_rg_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('doc_comprovante_endereco_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('doc_registro_conselho_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('doc_declaracao_rt_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('doc_declaracao_atividades_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('doc_termo_compromisso_path', sa.String(length=255), nullable=True))
        batch_op.alter_column('protocolo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('nome_completo',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('endereco_atendimento',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('uq_autonomos_email'), type_='unique')
        batch_op.drop_column('alvara_funcionamento_path')
        batch_op.drop_column('data_criacao')
        batch_op.drop_column('documentacao_anexada')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autonomos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documentacao_anexada', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('data_criacao', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('alvara_funcionamento_path', sa.VARCHAR(length=300), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_autonomos_email'), ['email'])
        batch_op.alter_column('endereco_atendimento',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('nome_completo',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.alter_column('protocolo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('doc_termo_compromisso_path')
        batch_op.drop_column('doc_declaracao_atividades_path')
        batch_op.drop_column('doc_declaracao_rt_path')
        batch_op.drop_column('doc_registro_conselho_path')
        batch_op.drop_column('doc_comprovante_endereco_path')
        batch_op.drop_column('doc_cpf_rg_path')
        batch_op.drop_column('doc_alvara_funcionamento_path')
        batch_op.drop_column('data_cadastro')

    # ### end Alembic commands ###
