"""Cria tabela de licenca de evento

Revision ID: 53fa6a0edc1d
Revises: 73eea21747a6
Create Date: 2025-07-27 14:29:01.731950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53fa6a0edc1d'
down_revision = '73eea21747a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licencas_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo', sa.String(length=50), nullable=True),
    sa.Column('nome_evento', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licencas_eventos')),
    sa.UniqueConstraint('protocolo', name=op.f('uq_licencas_eventos_protocolo'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('licencas_eventos')
    # ### end Alembic commands ###
