"""Cria tabela Fiscal simplificada com nome, cpf e matricula

Revision ID: 60b8b573d074
Revises: 34b855ceaf33
Create Date: 2025-07-23 14:43:12.963546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b8b573d074'
down_revision = '34b855ceaf33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_user')
    with op.batch_alter_table('fiscais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_fiscais_email'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_fiscais_cpf'), ['cpf'])
        batch_op.drop_constraint(batch_op.f('fk_fiscais_user_id_user'), type_='foreignkey')
        batch_op.drop_column('email')
        batch_op.drop_column('user_id')
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiscais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_fiscais_user_id_user'), 'user', ['user_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_fiscais_cpf'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_fiscais_email'), ['email'])
        batch_op.drop_column('cpf')

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), nullable=True),
    sa.Column('funcao', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('telefone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('nome', sa.VARCHAR(length=120), nullable=False),
    sa.Column('matricula', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula', name=op.f('uq_user_matricula'))
    )
    # ### end Alembic commands ###
