"""Adiciona campo de assinatura ao fiscal

Revision ID: 659cbb9b6ff7
Revises: 9a3e88ef6693
Create Date: 2025-07-31 18:22:56.021720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659cbb9b6ff7'
down_revision = '9a3e88ef6693'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiscais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caminho_assinatura', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fiscais', schema=None) as batch_op:
        batch_op.drop_column('caminho_assinatura')

    # ### end Alembic commands ###
