"""Atualiza o modelo LicencaEvento com todos os campos do formulário

Revision ID: 6bd1516aa6ac
Revises: 0530759d1bf6
Create Date: 2025-08-02 21:00:01.854191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '6bd1516aa6ac'
down_revision = '0530759d1bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipos_evento', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('vende_bebidas', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('tipo_casco', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('usa_estrutura_montavel', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('usa_churrasqueira', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('churrasqueira_tipo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('churrasqueira_gas_validade', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('usa_fritadeira', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('fritadeira_gas_validade', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('manipula_alimentos', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('tem_pia', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('doc_bombeiros_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('doc_cpf_cnpj_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('doc_alvara_local_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('doc_autorizacao_rua_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('tipo_evento')
        batch_op.drop_column('estrutura_detalhes')
        batch_op.drop_column('documentacao_anexada')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('documentacao_anexada', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('estrutura_detalhes', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('tipo_evento', sqlite.JSON(), nullable=True))
        batch_op.drop_column('doc_autorizacao_rua_path')
        batch_op.drop_column('doc_alvara_local_path')
        batch_op.drop_column('doc_cpf_cnpj_path')
        batch_op.drop_column('doc_bombeiros_path')
        batch_op.drop_column('tem_pia')
        batch_op.drop_column('manipula_alimentos')
        batch_op.drop_column('fritadeira_gas_validade')
        batch_op.drop_column('usa_fritadeira')
        batch_op.drop_column('churrasqueira_gas_validade')
        batch_op.drop_column('churrasqueira_tipo')
        batch_op.drop_column('usa_churrasqueira')
        batch_op.drop_column('usa_estrutura_montavel')
        batch_op.drop_column('tipo_casco')
        batch_op.drop_column('vende_bebidas')
        batch_op.drop_column('tipos_evento')

    # ### end Alembic commands ###
