"""Adiciona data_validade e alvara_pdf_path a licenca_evento

Revision ID: 6d8c7ef18292
Revises: eec998b93f87
Create Date: 2025-07-28 17:58:36.029708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8c7ef18292'
down_revision = 'eec998b93f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_validade', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('alvara_pdf_path', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_eventos', schema=None) as batch_op:
        batch_op.drop_column('alvara_pdf_path')
        batch_op.drop_column('data_validade')

    # ### end Alembic commands ###
