"""Adiciona relacionamento entre notificacoes e funcionarios

Revision ID: 7251711ac49e
Revises: cf76f873a7bc
Create Date: 2025-08-07 13:01:04.778693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7251711ac49e'
down_revision = 'cf76f873a7bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacao_fiscais',
    sa.Column('notificacao_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], name=op.f('fk_notificacao_fiscais_funcionario_id_funcionarios')),
    sa.ForeignKeyConstraint(['notificacao_id'], ['notificacoes.id'], name=op.f('fk_notificacao_fiscais_notificacao_id_notificacoes')),
    sa.PrimaryKeyConstraint('notificacao_id', 'funcionario_id', name=op.f('pk_notificacao_fiscais'))
    )
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo_notificacao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('descricao_irregularidade', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('prazo_regularizacao', sa.String(length=50), nullable=True))
        batch_op.drop_index(batch_op.f('ix_notificacoes_notificado_cpf_cnpj'))
        batch_op.drop_column('notificado_cpf_cnpj')
        batch_op.drop_column('irregularidades_constatadas')
        batch_op.drop_column('observacoes_adicionais')
        batch_op.drop_column('fiscal_matricula')
        batch_op.drop_column('cpf_vinculado')
        batch_op.drop_column('prazo')
        batch_op.drop_column('data_vistoria_origem')
        batch_op.drop_column('fiscal_nome')
        batch_op.drop_column('justificativa_parecer')
        batch_op.drop_column('fiscal_responsavel')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fiscal_responsavel', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('justificativa_parecer', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('fiscal_nome', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('data_vistoria_origem', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('prazo', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('cpf_vinculado', sa.VARCHAR(length=14), nullable=True))
        batch_op.add_column(sa.Column('fiscal_matricula', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('observacoes_adicionais', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('irregularidades_constatadas', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('notificado_cpf_cnpj', sa.VARCHAR(length=18), nullable=True))
        batch_op.create_index(batch_op.f('ix_notificacoes_notificado_cpf_cnpj'), ['notificado_cpf_cnpj'], unique=False)
        batch_op.drop_column('prazo_regularizacao')
        batch_op.drop_column('descricao_irregularidade')
        batch_op.drop_column('motivo_notificacao')

    op.drop_table('notificacao_fiscais')
    # ### end Alembic commands ###
