"""Reestrutura tabelas de licenca em Empresa, Autonomo e Evento

Revision ID: 73eea21747a6
Revises: ef7d71545017
Create Date: 2025-07-26 18:55:27.606382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '73eea21747a6'
down_revision = 'ef7d71545017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licencas_autonomos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo', sa.String(length=50), nullable=False),
    sa.Column('ano_exercicio', sa.String(length=4), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('autonomo_id', sa.Integer(), nullable=False),
    sa.Column('descricao_atividade', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['autonomo_id'], ['autonomos.id'], name=op.f('fk_licencas_autonomos_autonomo_id_autonomos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licencas_autonomos')),
    sa.UniqueConstraint('protocolo', name=op.f('uq_licencas_autonomos_protocolo'))
    )
    op.create_table('licencas_empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo', sa.String(length=50), nullable=False),
    sa.Column('ano_exercicio', sa.String(length=4), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo_atividade', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_licencas_empresas_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licencas_empresas')),
    sa.UniqueConstraint('protocolo', name=op.f('uq_licencas_empresas_protocolo'))
    )
    op.drop_table('licencas')
    op.drop_table('licencas_eventos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licencas_eventos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('protocolo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('nome_evento', sa.VARCHAR(length=150), nullable=False),
    sa.Column('organizador_nome', sa.VARCHAR(length=150), nullable=False),
    sa.Column('organizador_cpf_cnpj', sa.VARCHAR(length=18), nullable=False),
    sa.Column('local_evento', sa.VARCHAR(length=250), nullable=True),
    sa.Column('data_inicio', sa.DATE(), nullable=True),
    sa.Column('data_fim', sa.DATE(), nullable=True),
    sa.Column('publico_estimado', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('data_solicitacao', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licencas_eventos')),
    sa.UniqueConstraint('protocolo', name=op.f('uq_licencas_eventos_protocolo'))
    )
    op.create_table('licencas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('empresa_id', sa.INTEGER(), nullable=True),
    sa.Column('protocolo_licencas', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ano_exercicio', sa.VARCHAR(), nullable=True),
    sa.Column('tipo_atividade', sa.VARCHAR(), nullable=True),
    sa.Column('descricao_atividade', sa.TEXT(), nullable=True),
    sa.Column('possui_local_fisico', sa.VARCHAR(), nullable=True),
    sa.Column('necessita_rt', sa.VARCHAR(), nullable=True),
    sa.Column('rt_declaracao_path', sa.VARCHAR(), nullable=True),
    sa.Column('vende_controlados', sa.VARCHAR(), nullable=True),
    sa.Column('afe_path', sa.VARCHAR(), nullable=True),
    sa.Column('vende_animais', sa.VARCHAR(), nullable=True),
    sa.Column('rt_vet_declaracao_path', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('data_solicitacao', sa.DATETIME(), nullable=True),
    sa.Column('autonomo_id', sa.INTEGER(), nullable=True),
    sa.Column('endereco_completo_licenca', sa.TEXT(), nullable=True),
    sa.Column('rt_info', sqlite.JSON(), nullable=True),
    sa.Column('afe_info', sqlite.JSON(), nullable=True),
    sa.Column('vende_retinoicos', sa.VARCHAR(length=10), nullable=True),
    sa.Column('retinoicos_info', sqlite.JSON(), nullable=True),
    sa.Column('retinoicos_path', sa.VARCHAR(length=300), nullable=True),
    sa.Column('rt_vet_info', sqlite.JSON(), nullable=True),
    sa.Column('realizou_controle_pragas', sa.VARCHAR(length=10), nullable=True),
    sa.Column('controle_pragas_info', sqlite.JSON(), nullable=True),
    sa.Column('controle_pragas_path', sa.VARCHAR(length=300), nullable=True),
    sa.Column('doc_foto_path', sa.VARCHAR(length=300), nullable=True),
    sa.ForeignKeyConstraint(['autonomo_id'], ['autonomos.id'], name=op.f('fk_licencas_autonomo_id_autonomos')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('protocolo_licencas', name=op.f('uq_licencas_protocolo_licencas'))
    )
    op.drop_table('licencas_empresas')
    op.drop_table('licencas_autonomos')
    # ### end Alembic commands ###
