"""Atualiza modelo PessoaFisica com campos detalhados

Revision ID: 9092047da7d8
Revises: 6bd1516aa6ac
Create Date: 2025-08-03 16:42:52.056635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '9092047da7d8'
down_revision = '6bd1516aa6ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoas_fisicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recebeu_notificacao', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('foi_objeto_denuncia', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('recebeu_visita', sa.Boolean(), nullable=True))
        batch_op.alter_column('finalidade_cadastro',
               existing_type=sqlite.JSON(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('situacao_local')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pessoas_fisicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('situacao_local', sqlite.JSON(), nullable=True))
        batch_op.alter_column('finalidade_cadastro',
               existing_type=sa.String(length=100),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.drop_column('recebeu_visita')
        batch_op.drop_column('foi_objeto_denuncia')
        batch_op.drop_column('recebeu_notificacao')

    # ### end Alembic commands ###
