"""Adiciona campo de anexos de pendencia a LicencaEmpresa

Revision ID: 91731dbf35b5
Revises: 9092047da7d8
Create Date: 2025-08-03 17:41:37.624815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91731dbf35b5'
down_revision = '9092047da7d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anexos_pendencia', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_empresa', schema=None) as batch_op:
        batch_op.drop_column('anexos_pendencia')

    # ### end Alembic commands ###
