"""Adiciona campos de fiscal ao modelo User

Revision ID: 939875c276ca
Revises: 423732c4aa16
Create Date: 2025-07-23 14:11:39.228856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939875c276ca'
down_revision = '423732c4aa16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autos_infracao', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_autos_infracao_protocolo_auto'), ['protocolo_auto'])

    with op.batch_alter_table('denuncias', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_denuncias_protocolo_denuncia'), ['protocolo_denuncia'])

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_empresas_cnpj'), ['cnpj'])

    with op.batch_alter_table('estoque_receituario', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_estoque_receituario_tipo_id'), ['tipo_id'])

    with op.batch_alter_table('licencas', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_licencas_protocolo_licencas'), ['protocolo_licencas'])

    with op.batch_alter_table('licencas_publicas', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_licencas_publicas_protocolo_licencas_publicas'), ['protocolo_licencas_publicas'])

    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_notificacoes_protocolo_notificacao'), ['protocolo_notificacao'])

    with op.batch_alter_table('solicitacoes_calazar', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_solicitacoes_calazar_protocolo'), ['protocolo'])

    with op.batch_alter_table('solicitacoes_receituario', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_solicitacoes_receituario_protocolo'), ['protocolo'])

    with op.batch_alter_table('tipos_receituario', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_tipos_receituario_nome'), ['nome'])
        batch_op.create_unique_constraint(batch_op.f('uq_tipos_receituario_sigla'), ['sigla'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('matricula', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('funcao', sa.String(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_unique_constraint(batch_op.f('uq_user_matricula'), ['matricula'])

    with op.batch_alter_table('vistoria', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_vistoria_protocolo_vistoria'), ['protocolo_vistoria'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vistoria', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_vistoria_protocolo_vistoria'), type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_matricula'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_column('funcao')
        batch_op.drop_column('telefone')
        batch_op.drop_column('email')
        batch_op.drop_column('matricula')
        batch_op.drop_column('nome')

    with op.batch_alter_table('tipos_receituario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_tipos_receituario_sigla'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_tipos_receituario_nome'), type_='unique')

    with op.batch_alter_table('solicitacoes_receituario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_solicitacoes_receituario_protocolo'), type_='unique')

    with op.batch_alter_table('solicitacoes_calazar', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_solicitacoes_calazar_protocolo'), type_='unique')

    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_notificacoes_protocolo_notificacao'), type_='unique')

    with op.batch_alter_table('licencas_publicas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_licencas_publicas_protocolo_licencas_publicas'), type_='unique')

    with op.batch_alter_table('licencas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_licencas_protocolo_licencas'), type_='unique')

    with op.batch_alter_table('estoque_receituario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_estoque_receituario_tipo_id'), type_='unique')

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_empresas_cnpj'), type_='unique')

    with op.batch_alter_table('denuncias', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_denuncias_protocolo_denuncia'), type_='unique')

    with op.batch_alter_table('autos_infracao', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_autos_infracao_protocolo_auto'), type_='unique')

    # ### end Alembic commands ###
