"""Adiciona campo de observacoes a licenca

Revision ID: 9a3e88ef6693
Revises: 1fa78f451c44
Create Date: 2025-07-30 17:36:15.907125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3e88ef6693'
down_revision = '1fa78f451c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_empresas', schema=None) as batch_op:
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###
