"""Adiciona campos de resposta a pendencias em LicencasPublicas

Revision ID: a5e61b6b6f8f
Revises: cfa2dff1caf1
Create Date: 2025-08-04 17:22:30.550372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e61b6b6f8f'
down_revision = 'cfa2dff1caf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_publicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resposta_pendencia_texto', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('anexo_pendencia_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_publicas', schema=None) as batch_op:
        batch_op.drop_column('anexo_pendencia_path')
        batch_op.drop_column('resposta_pendencia_texto')

    # ### end Alembic commands ###
