"""Reestrutura tabelas de licenca com todos os campos

Revision ID: aa00b4f621c7
Revises: df318ad806c0
Create Date: 2025-07-28 14:42:34.044602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa00b4f621c7'
down_revision = 'df318ad806c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_autonomos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_validade', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_autonomos', schema=None) as batch_op:
        batch_op.drop_column('data_validade')

    # ### end Alembic commands ###
