"""Adiciona campo para manipulação de medicamentos

Revision ID: aaa4488fc806
Revises: da4e72b2901e
Create Date: 2025-07-31 22:37:28.643553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa4488fc806'
down_revision = 'da4e72b2901e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('realiza_manipulacao', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_empresa', schema=None) as batch_op:
        batch_op.drop_column('realiza_manipulacao')

    # ### end Alembic commands ###
