"""Adiciona data de validade a licenca de empresa

Revision ID: ab275eea8b97
Revises: f14209ebc262
Create Date: 2025-07-27 15:04:04.264926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab275eea8b97'
down_revision = 'f14209ebc262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_validade', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_empresas', schema=None) as batch_op:
        batch_op.drop_column('data_validade')

    # ### end Alembic commands ###
