"""Cria tabela de protocolo sequencial

Revision ID: b0401a63e1d3
Revises: 3b5ba61796b6
Create Date: 2025-07-29 18:24:06.894469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0401a63e1d3'
down_revision = '3b5ba61796b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocolo_sequencial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('ultimo_numero', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_protocolo_sequencial')),
    sa.UniqueConstraint('ano', 'categoria', name='_ano_categoria_uc')
    )
    op.drop_table('protocolos_sequenciais')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('protocolos_sequenciais',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ano', sa.INTEGER(), nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ultimo_numero', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ano', 'categoria', name=op.f('_ano_categoria_uc'))
    )
    op.drop_table('protocolo_sequencial')
    # ### end Alembic commands ###
