"""Adiciona campo cpf_vinculado em Notificacoes

Revision ID: b67faa505780
Revises: db98bbbc0051
Create Date: 2025-08-05 16:42:42.592494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b67faa505780'
down_revision = 'db98bbbc0051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf_vinculado', sa.String(length=14), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_column('cpf_vinculado')

    # ### end Alembic commands ###
