"""Adiciona campos de cpf_cnpj a vistorias, denuncias e notificacoes

Revision ID: bf6c138d3dee
Revises: aa00b4f621c7
Create Date: 2025-07-28 17:30:56.552822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf6c138d3dee'
down_revision = 'aa00b4f621c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('denuncias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('denunciado_cpf_cnpj', sa.String(length=18), nullable=True))
        batch_op.create_index(batch_op.f('ix_denuncias_denunciado_cpf_cnpj'), ['denunciado_cpf_cnpj'], unique=False)

    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notificado_cpf_cnpj', sa.String(length=18), nullable=True))
        batch_op.create_index(batch_op.f('ix_notificacoes_notificado_cpf_cnpj'), ['notificado_cpf_cnpj'], unique=False)

    with op.batch_alter_table('vistoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf_cnpj_vinculado', sa.String(length=18), nullable=True))
        batch_op.create_index(batch_op.f('ix_vistoria_cpf_cnpj_vinculado'), ['cpf_cnpj_vinculado'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vistoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vistoria_cpf_cnpj_vinculado'))
        batch_op.drop_column('cpf_cnpj_vinculado')

    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notificacoes_notificado_cpf_cnpj'))
        batch_op.drop_column('notificado_cpf_cnpj')

    with op.batch_alter_table('denuncias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_denuncias_denunciado_cpf_cnpj'))
        batch_op.drop_column('denunciado_cpf_cnpj')

    # ### end Alembic commands ###
