"""Completa o modelo LicencaAutonomo

Revision ID: c42b1dd60aec
Revises: d79f98562c36
Create Date: 2025-08-02 17:06:05.602169

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'c42b1dd60aec'
down_revision = 'd79f98562c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_autonomos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rt_nome', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('rt_cpf', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('rt_conselho', sa.String(length=50), nullable=True))
        batch_op.alter_column('local_atuacao_endereco',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('local_atuacao_referencia',
               existing_type=sa.VARCHAR(length=250),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('ano_exercicio')
        batch_op.drop_column('rt_info')
        batch_op.drop_column('justificativa_status')
        batch_op.drop_column('data_validade')
        batch_op.drop_column('alvara_pdf_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_autonomos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alvara_pdf_path', sa.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('data_validade', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('justificativa_status', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('rt_info', sqlite.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ano_exercicio', sa.VARCHAR(length=4), nullable=True))
        batch_op.alter_column('local_atuacao_referencia',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.alter_column('local_atuacao_endereco',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=250),
               existing_nullable=True)
        batch_op.drop_column('rt_conselho')
        batch_op.drop_column('rt_cpf')
        batch_op.drop_column('rt_nome')

    # ### end Alembic commands ###
