"""Adiciona campos de MEI e taxa à licença de empresa

Revision ID: c542d715dfd1
Revises: aaa4488fc806
Create Date: 2025-08-01 16:00:43.239638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c542d715dfd1'
down_revision = 'aaa4488fc806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('e_mei', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('comprovante_taxa_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_empresa', schema=None) as batch_op:
        batch_op.drop_column('comprovante_taxa_path')
        batch_op.drop_column('e_mei')

    # ### end Alembic commands ###
