"""Adiciona caminho do alvara ao modelo LicencaAutonomo

Revision ID: cd86cc2eedd5
Revises: 4b27cb561c8a
Create Date: 2025-08-01 18:38:39.153839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd86cc2eedd5'
down_revision = '4b27cb561c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_autonomos', schema=None) as batch_op:
        batch_op.alter_column('alvara_pdf_path',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_autonomos', schema=None) as batch_op:
        batch_op.alter_column('alvara_pdf_path',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)

    # ### end Alembic commands ###
