"""Torna fiscal_responsavel opcional em Notificacoes

Revision ID: cf76f873a7bc
Revises: f43d8b04c943
Create Date: 2025-08-05 16:53:50.411600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf76f873a7bc'
down_revision = 'f43d8b04c943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.alter_column('fiscal_responsavel',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.alter_column('fiscal_responsavel',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
