"""Adiciona data_validade a LicencasPublicas

Revision ID: cfa2dff1caf1
Revises: 0ad5efa0eb76
Create Date: 2025-08-04 16:51:54.832412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfa2dff1caf1'
down_revision = '0ad5efa0eb76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_publicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('data_validade', sa.Date(), nullable=True))
        batch_op.drop_column('justificativa_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_publicas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('justificativa_status', sa.TEXT(), nullable=True))
        batch_op.drop_column('data_validade')
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###
