"""Adiciona todos os campos da licença de empresa

Revision ID: da4e72b2901e
Revises: 2b01b1538d82
Create Date: 2025-07-31 21:52:14.499803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'da4e72b2901e'
down_revision = '2b01b1538d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licencas_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocolo', sa.String(length=20), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('ano_exercicio', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('alvara_pdf_path', sa.String(length=255), nullable=True),
    sa.Column('tipo_atividade', sa.String(length=100), nullable=True),
    sa.Column('descricao_atividade', sa.Text(), nullable=True),
    sa.Column('possui_local_fisico', sa.String(length=10), nullable=True),
    sa.Column('endereco_completo', sa.String(length=300), nullable=True),
    sa.Column('necessita_rt', sa.String(length=10), nullable=True),
    sa.Column('rt_nome', sa.String(length=150), nullable=True),
    sa.Column('rt_cpf', sa.String(length=20), nullable=True),
    sa.Column('rt_conselho', sa.String(length=50), nullable=True),
    sa.Column('rt_numero_conselho', sa.String(length=50), nullable=True),
    sa.Column('rt_declaracao_path', sa.String(length=255), nullable=True),
    sa.Column('vende_controlados', sa.String(length=10), nullable=True),
    sa.Column('afe_numero', sa.String(length=100), nullable=True),
    sa.Column('afe_anexo_path', sa.String(length=255), nullable=True),
    sa.Column('vende_retinoicos', sa.String(length=10), nullable=True),
    sa.Column('retinoicos_numero_autorizacao', sa.String(length=100), nullable=True),
    sa.Column('retinoicos_data_autorizacao', sa.Date(), nullable=True),
    sa.Column('retinoicos_validade', sa.Date(), nullable=True),
    sa.Column('retinoicos_anexo_path', sa.String(length=255), nullable=True),
    sa.Column('vende_animais', sa.String(length=10), nullable=True),
    sa.Column('rt_vet_nome', sa.String(length=150), nullable=True),
    sa.Column('rt_vet_cpf', sa.String(length=20), nullable=True),
    sa.Column('rt_vet_crmv', sa.String(length=50), nullable=True),
    sa.Column('rt_vet_declaracao_path', sa.String(length=255), nullable=True),
    sa.Column('realizou_dedetizacao', sa.String(length=10), nullable=True),
    sa.Column('dedetizacao_data', sa.Date(), nullable=True),
    sa.Column('dedetizacao_anexo_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_licencas_empresa_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licencas_empresa')),
    sa.UniqueConstraint('protocolo', name=op.f('uq_licencas_empresa_protocolo'))
    )
    op.drop_table('licencas_empresas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licencas_empresas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('protocolo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('ano_exercicio', sa.VARCHAR(length=4), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('data_solicitacao', sa.DATETIME(), nullable=True),
    sa.Column('empresa_id', sa.INTEGER(), nullable=False),
    sa.Column('tipo_atividade', sa.VARCHAR(length=100), nullable=True),
    sa.Column('possui_local_fisico', sa.VARCHAR(length=10), nullable=True),
    sa.Column('endereco_completo_licenca', sa.TEXT(), nullable=True),
    sa.Column('necessita_rt', sa.VARCHAR(length=10), nullable=True),
    sa.Column('rt_info', sqlite.JSON(), nullable=True),
    sa.Column('rt_declaracao_path', sa.VARCHAR(length=300), nullable=True),
    sa.Column('vende_controlados', sa.VARCHAR(length=10), nullable=True),
    sa.Column('afe_info', sqlite.JSON(), nullable=True),
    sa.Column('afe_path', sa.VARCHAR(length=300), nullable=True),
    sa.Column('vende_retinoicos', sa.VARCHAR(length=10), nullable=True),
    sa.Column('retinoicos_info', sqlite.JSON(), nullable=True),
    sa.Column('retinoicos_path', sa.VARCHAR(length=300), nullable=True),
    sa.Column('vende_animais', sa.VARCHAR(length=10), nullable=True),
    sa.Column('rt_vet_info', sqlite.JSON(), nullable=True),
    sa.Column('rt_vet_declaracao_path', sa.VARCHAR(length=300), nullable=True),
    sa.Column('realizou_controle_pragas', sa.VARCHAR(length=10), nullable=True),
    sa.Column('controle_pragas_info', sqlite.JSON(), nullable=True),
    sa.Column('controle_pragas_path', sa.VARCHAR(length=300), nullable=True),
    sa.Column('faz_transporte', sa.VARCHAR(length=10), nullable=True),
    sa.Column('transporte_descricao', sa.TEXT(), nullable=True),
    sa.Column('descricao_atividade', sa.TEXT(), nullable=True),
    sa.Column('data_validade', sa.DATE(), nullable=True),
    sa.Column('justificativa_status', sa.TEXT(), nullable=True),
    sa.Column('alvara_pdf_path', sa.VARCHAR(length=300), nullable=True),
    sa.Column('rt_nome', sa.VARCHAR(length=150), nullable=True),
    sa.Column('rt_conselho', sa.VARCHAR(length=50), nullable=True),
    sa.Column('rt_numero', sa.VARCHAR(length=20), nullable=True),
    sa.Column('observacoes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_licencas_empresas_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_licencas_empresas')),
    sa.UniqueConstraint('protocolo', name=op.f('uq_licencas_empresas_protocolo'))
    )
    op.drop_table('licencas_empresa')
    # ### end Alembic commands ###
