"""Descreva a alteração que você fez

Revision ID: db98bbbc0051
Revises: a5e61b6b6f8f
Create Date: 2025-08-05 15:14:37.908248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db98bbbc0051'
down_revision = 'a5e61b6b6f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('denuncias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acao_gerada', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('denuncias', schema=None) as batch_op:
        batch_op.drop_column('acao_gerada')

    # ### end Alembic commands ###
