"""Adiciona campos de alvara e justificativa as licencas

Revision ID: df318ad806c0
Revises: ab275eea8b97
Create Date: 2025-07-27 16:18:46.492594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df318ad806c0'
down_revision = 'ab275eea8b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_autonomos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('justificativa_status', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('alvara_pdf_path', sa.String(length=300), nullable=True))

    with op.batch_alter_table('licencas_empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('justificativa_status', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('alvara_pdf_path', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_empresas', schema=None) as batch_op:
        batch_op.drop_column('alvara_pdf_path')
        batch_op.drop_column('justificativa_status')

    with op.batch_alter_table('licencas_autonomos', schema=None) as batch_op:
        batch_op.drop_column('alvara_pdf_path')
        batch_op.drop_column('justificativa_status')

    # ### end Alembic commands ###
