"""Adiciona campo para alvara de funcionamento em autonomos

Revision ID: e0aace96861f
Revises: 60b8b573d074
Create Date: 2025-07-23 15:47:53.900219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0aace96861f'
down_revision = '60b8b573d074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autonomos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('orgao_expedidor', sa.String(length=20), nullable=True),
    sa.Column('uf_rg', sa.String(length=2), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('telefone_celular', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('endereco_atendimento', sa.String(length=200), nullable=True),
    sa.Column('tipo_local', sa.String(length=50), nullable=True),
    sa.Column('profissao', sa.String(length=100), nullable=True),
    sa.Column('conselho_classe', sa.String(length=50), nullable=True),
    sa.Column('numero_registro_profissional', sa.String(length=50), nullable=True),
    sa.Column('atividades_exercidas', sa.Text(), nullable=True),
    sa.Column('inscricao_municipal', sa.String(length=50), nullable=True),
    sa.Column('documentacao_anexada', sa.JSON(), nullable=True),
    sa.Column('alvara_funcionamento_path', sa.String(length=300), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_autonomos')),
    sa.UniqueConstraint('cpf', name=op.f('uq_autonomos_cpf')),
    sa.UniqueConstraint('email', name=op.f('uq_autonomos_email'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('autonomos')
    # ### end Alembic commands ###
