"""Adiciona campos de observacoes e anexos a LicencaEvento

Revision ID: e0d25a365ad3
Revises: 4687deae9ab3
Create Date: 2025-08-03 19:48:03.355320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d25a365ad3'
down_revision = '4687deae9ab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('anexos_pendencia', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_eventos', schema=None) as batch_op:
        batch_op.drop_column('anexos_pendencia')
        batch_op.drop_column('observacoes')

    # ### end Alembic commands ###
