"""Add cpf_vinculado to autos_infracao

Revision ID: ed4536ca94fe
Revises: 7251711ac49e
Create Date: 2025-08-12 22:39:30.434473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4536ca94fe'
down_revision = '7251711ac49e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autos_infracao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf_vinculado', sa.String(length=14), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autos_infracao', schema=None) as batch_op:
        batch_op.drop_column('cpf_vinculado')

    # ### end Alembic commands ###
