"""Completa a tabela de licenca de evento com todos os campos

Revision ID: eec998b93f87
Revises: bf6c138d3dee
Create Date: 2025-07-28 17:40:47.932923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec998b93f87'
down_revision = 'bf6c138d3dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_eventos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('solicitante_nome', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('solicitante_cpf_cnpj', sa.String(length=18), nullable=False))
        batch_op.add_column(sa.Column('solicitante_rg', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('solicitante_telefone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('solicitante_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('solicitante_endereco', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('tipo_evento', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('local_evento', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('data_inicio', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_fim', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('horario', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('estrutura', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('bombeiros_liberacao', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('bombeiros_anexo_path', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('documentacao_anexada', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_eventos', schema=None) as batch_op:
        batch_op.drop_column('documentacao_anexada')
        batch_op.drop_column('bombeiros_anexo_path')
        batch_op.drop_column('bombeiros_liberacao')
        batch_op.drop_column('estrutura')
        batch_op.drop_column('horario')
        batch_op.drop_column('data_fim')
        batch_op.drop_column('data_inicio')
        batch_op.drop_column('local_evento')
        batch_op.drop_column('tipo_evento')
        batch_op.drop_column('solicitante_endereco')
        batch_op.drop_column('solicitante_email')
        batch_op.drop_column('solicitante_telefone')
        batch_op.drop_column('solicitante_rg')
        batch_op.drop_column('solicitante_cpf_cnpj')
        batch_op.drop_column('solicitante_nome')

    # ### end Alembic commands ###
