"""Expande a tabela de licencas com campos do questionario

Revision ID: ef7d71545017
Revises: 37e43484d25c
Create Date: 2025-07-26 14:46:50.251470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7d71545017'
down_revision = '37e43484d25c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco_completo_licenca', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rt_info', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('afe_info', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('vende_retinoicos', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('retinoicos_info', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('retinoicos_path', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('rt_vet_info', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('realizou_controle_pragas', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('controle_pragas_info', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('controle_pragas_path', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('doc_foto_path', sa.String(length=300), nullable=True))
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('endereco_referencia')
        batch_op.drop_column('rt_vet_conselho')
        batch_op.drop_column('rt_vet_cpf')
        batch_op.drop_column('afe_numero')
        batch_op.drop_column('data_vencimento')
        batch_op.drop_column('endereco_numero')
        batch_op.drop_column('certificado_dedetizacao_path')
        batch_op.drop_column('rt_vet_numero_conselho')
        batch_op.drop_column('realizou_dedetizacao')
        batch_op.drop_column('rt_contato')
        batch_op.drop_column('rt_conselho')
        batch_op.drop_column('justificativa_status')
        batch_op.drop_column('data_emissao')
        batch_op.drop_column('endereco_rua')
        batch_op.drop_column('endereco_bairro')
        batch_op.drop_column('rt_cpf')
        batch_op.drop_column('manipula_medicamentos')
        batch_op.drop_column('rt_numero_conselho')
        batch_op.drop_column('ano_abertura_empresa')
        batch_op.drop_column('atividade_principal_descrita')
        batch_op.drop_column('rt_nome')
        batch_op.drop_column('alvara_pdf_path')
        batch_op.drop_column('data_dedetizacao')
        batch_op.drop_column('rt_vet_nome')
        batch_op.drop_column('rt_vet_contato')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rt_vet_contato', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('rt_vet_nome', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('data_dedetizacao', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('alvara_pdf_path', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('rt_nome', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('atividade_principal_descrita', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('ano_abertura_empresa', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('rt_numero_conselho', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('manipula_medicamentos', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('rt_cpf', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('endereco_bairro', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('endereco_rua', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('data_emissao', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('justificativa_status', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('rt_conselho', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('rt_contato', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('realizou_dedetizacao', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('rt_vet_numero_conselho', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('certificado_dedetizacao_path', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('endereco_numero', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('data_vencimento', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('afe_numero', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('rt_vet_cpf', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('rt_vet_conselho', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('endereco_referencia', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('empresa_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('doc_foto_path')
        batch_op.drop_column('controle_pragas_path')
        batch_op.drop_column('controle_pragas_info')
        batch_op.drop_column('realizou_controle_pragas')
        batch_op.drop_column('rt_vet_info')
        batch_op.drop_column('retinoicos_path')
        batch_op.drop_column('retinoicos_info')
        batch_op.drop_column('vende_retinoicos')
        batch_op.drop_column('afe_info')
        batch_op.drop_column('rt_info')
        batch_op.drop_column('endereco_completo_licenca')

    # ### end Alembic commands ###
