"""Adiciona campos detalhados aos modelos de licenca

Revision ID: f14209ebc262
Revises: 53fa6a0edc1d
Create Date: 2025-07-27 14:40:43.362953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f14209ebc262'
down_revision = '53fa6a0edc1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_autonomos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nacionalidade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('estado_civil', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('local_atuacao_endereco', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('local_atuacao_tipo', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('local_atuacao_referencia', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('possui_rt', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('rt_info', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('rt_declaracao_path', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('usa_quimicos', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('usa_perfuro', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('faz_invasivo', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('invasivo_descricao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('doc_identidade_path', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('doc_cpf_path', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('doc_residencia_path', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('doc_formacao_path', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('doc_dedetizacao_path', sa.String(length=300), nullable=True))

    with op.batch_alter_table('licencas_empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('possui_local_fisico', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('endereco_completo_licenca', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('necessita_rt', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('rt_info', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('rt_declaracao_path', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('vende_controlados', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('afe_info', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('afe_path', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('vende_retinoicos', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('retinoicos_info', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('retinoicos_path', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('vende_animais', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('rt_vet_info', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('rt_vet_declaracao_path', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('realizou_controle_pragas', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('controle_pragas_info', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('controle_pragas_path', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('faz_transporte', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('transporte_descricao', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('descricao_atividade', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_empresas', schema=None) as batch_op:
        batch_op.drop_column('descricao_atividade')
        batch_op.drop_column('transporte_descricao')
        batch_op.drop_column('faz_transporte')
        batch_op.drop_column('controle_pragas_path')
        batch_op.drop_column('controle_pragas_info')
        batch_op.drop_column('realizou_controle_pragas')
        batch_op.drop_column('rt_vet_declaracao_path')
        batch_op.drop_column('rt_vet_info')
        batch_op.drop_column('vende_animais')
        batch_op.drop_column('retinoicos_path')
        batch_op.drop_column('retinoicos_info')
        batch_op.drop_column('vende_retinoicos')
        batch_op.drop_column('afe_path')
        batch_op.drop_column('afe_info')
        batch_op.drop_column('vende_controlados')
        batch_op.drop_column('rt_declaracao_path')
        batch_op.drop_column('rt_info')
        batch_op.drop_column('necessita_rt')
        batch_op.drop_column('endereco_completo_licenca')
        batch_op.drop_column('possui_local_fisico')

    with op.batch_alter_table('licencas_autonomos', schema=None) as batch_op:
        batch_op.drop_column('doc_dedetizacao_path')
        batch_op.drop_column('doc_formacao_path')
        batch_op.drop_column('doc_residencia_path')
        batch_op.drop_column('doc_cpf_path')
        batch_op.drop_column('doc_identidade_path')
        batch_op.drop_column('invasivo_descricao')
        batch_op.drop_column('faz_invasivo')
        batch_op.drop_column('usa_perfuro')
        batch_op.drop_column('usa_quimicos')
        batch_op.drop_column('rt_declaracao_path')
        batch_op.drop_column('rt_info')
        batch_op.drop_column('possui_rt')
        batch_op.drop_column('local_atuacao_referencia')
        batch_op.drop_column('local_atuacao_tipo')
        batch_op.drop_column('local_atuacao_endereco')
        batch_op.drop_column('estado_civil')
        batch_op.drop_column('nacionalidade')

    # ### end Alembic commands ###
