"""Adiciona campo fiscal_responsavel em Notificacoes

Revision ID: f43d8b04c943
Revises: b67faa505780
Create Date: 2025-08-05 16:44:38.140979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f43d8b04c943'
down_revision = 'b67faa505780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fiscal_responsavel', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_column('fiscal_responsavel')

    # ### end Alembic commands ###
