"""Adiciona alvara de funcionamento a licenca autonomo

Revision ID: f9fb5b068c04
Revises: c42b1dd60aec
Create Date: 2025-08-02 17:30:31.187490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9fb5b068c04'
down_revision = 'c42b1dd60aec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_autonomos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doc_alvara_funcionamento_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licencas_autonomos', schema=None) as batch_op:
        batch_op.drop_column('doc_alvara_funcionamento_path')

    # ### end Alembic commands ###
